name: Build LaTeX Document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第二步：运行 LaTeX Action
      - name: LaTeX Action
        uses: fudan-mse/latex-action@v0.0.1
        with:
          root_file: resume.tex
          working_directory: Resumes/resume-template