name: Build LaTeX Document

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # First step: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Second step: Compile the LaTeX document
      - name: LaTeX Action
        uses: fudan-mse/latex-action@v0.0.1
        with:
          root_file: resume.tex
          working_directory: ./

      # Third step: Upload the PDF artifact
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-output
          path: ./resume.pdf